# syntax=docker/dockerfile:1
#
# Spilo, carrying the extension set and bootstrap SQL that Supabase's own
# Postgres image provides -- so Supabase can run on a Zalando-operated,
# Patroni-replicated cluster instead of a single unmanaged container.
#
# Two things this adds to stock Spilo:
#   1. The Supabase extensions, from the Pigsty APT repo (pg_net excepted --
#      see the builder stage below).
#   2. The Supabase migrations, executed by Patroni's bootstrap.post_init
#      callback. Unlike CloudNativePG, Spilo does run scripts from the image
#      at bootstrap, so this needs no separate Job and has no ordering race
#      with whatever deploys the rest of Supabase.

ARG PGVERSION=18

# renovate: datasource=docker depName=ghcr.io/zalando/spilo-18 versioning=regex:^(?<major>\d+)\.(?<minor>\d+)-p(?<patch>\d+)$
ARG SPILO_VERSION=4.1-p2

# renovate: datasource=github-releases depName=supabase/pg_net extractVersion=^v(?<version>.+)$
ARG PG_NET_VERSION=0.20.5

# Underscored to match curl's own tag format (curl-8_22_0), which is what
# Renovate reads; the build converts it to the dotted form for the tarball URL.
# renovate: datasource=github-tags depName=curl/curl extractVersion=^curl-(?<version>.+)$ versioning=regex:^(?<major>\d+)_(?<minor>\d+)_(?<patch>\d+)$
ARG CURL_VERSION=8_22_0


# --------------------------------------------------------------- pg_net build
# pg_net >= 0.20 calls curl_easy_header(), added in libcurl 7.83. Spilo is
# built on Ubuntu jammy, which ships 7.81 -- which is exactly why Pigsty's
# jammy pg_net package is frozen at 0.9.2 while its noble one tracks upstream.
#
# So: build a current libcurl and link it STATICALLY into pg_net.so. The
# runtime image keeps its own libcurl4 untouched for everything else that
# uses it. The trade is that this libcurl no longer receives distro security
# updates, so CURL_VERSION above is Renovate-tracked and the image is rebuilt
# weekly.
FROM ghcr.io/zalando/spilo-${PGVERSION}:${SPILO_VERSION} AS pg-net-builder
ARG PGVERSION
ARG PG_NET_VERSION
ARG CURL_VERSION
USER root
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
      build-essential ca-certificates curl pkg-config \
      libssl-dev zlib1g-dev postgresql-server-dev-${PGVERSION} \
 && rm -rf /var/lib/apt/lists/*

RUN CURL_DOTTED="$(echo "${CURL_VERSION}" | tr '_' '.')" \
 && curl -fsSL "https://curl.se/download/curl-${CURL_DOTTED}.tar.gz" | tar xz -C /tmp \
 && cd "/tmp/curl-${CURL_DOTTED}" \
 && ./configure --prefix=/opt/curl-static \
      --disable-shared --enable-static --with-openssl --with-zlib \
      --without-libpsl --without-libidn2 --disable-ldap --disable-ldaps \
      --disable-manual --without-brotli --without-zstd --without-nghttp2 \
      >/dev/null \
 && make -j"$(nproc)" >/dev/null && make install >/dev/null \
 && /opt/curl-static/bin/curl-config --version

# Two flag traps here, both from pg_net's Makefile:
#   PG_CPPFLAGS is assigned as "$(CPPFLAGS) -DEXTVERSION=..." -- overriding it
#     on the command line drops the version define and the build fails on an
#     undeclared EXTVERSION.
#   CPPFLAGS must therefore carry pg_config's own flags too, or -D_GNU_SOURCE
#     goes missing and locale_t is undeclared.
# And `make` must run as its own invocation before `make install`: DATA is set
# from $(wildcard sql/*--*.sql), evaluated when the makefile is parsed, and the
# versioned SQL file is generated by the build. A lone `make install` therefore
# installs the .so and control file but no installation script, and CREATE
# EXTENSION fails with "no installation script nor update path".
RUN PGBIN="/usr/lib/postgresql/${PGVERSION}/bin" \
 && curl -fsSL "https://github.com/supabase/pg_net/archive/refs/tags/v${PG_NET_VERSION}.tar.gz" \
      | tar xz -C /tmp \
 && cd "/tmp/pg_net-${PG_NET_VERSION}" \
 && CURL_LIBS="/opt/curl-static/lib/libcurl.a $(/opt/curl-static/bin/curl-config --static-libs | sed 's|-lcurl||')" \
 && make PG_CONFIG="$PGBIN/pg_config" \
      CPPFLAGS="$($PGBIN/pg_config --cppflags) -I/opt/curl-static/include" \
      SHLIB_LINK="$CURL_LIBS" \
 && make install PG_CONFIG="$PGBIN/pg_config" DESTDIR=/tmp/pg_net-install \
      CPPFLAGS="$($PGBIN/pg_config --cppflags) -I/opt/curl-static/include" \
      SHLIB_LINK="$CURL_LIBS" \
 && echo "--- pg_net.so must NOT link libcurl.so ---" \
 && ! ldd "/tmp/pg_net-install/usr/lib/postgresql/${PGVERSION}/lib/pg_net.so" | grep -q libcurl


# -------------------------------------------------------------------- runtime
FROM ghcr.io/zalando/spilo-${PGVERSION}:${SPILO_VERSION}
ARG PGVERSION
USER root
ENV DEBIAN_FRONTEND=noninteractive

# Pigsty packages the Supabase extension set as .debs for PG 12-18 on jammy.
RUN apt-get update \
 && apt-get install -y --no-install-recommends curl ca-certificates gnupg lsb-release \
 && mkdir -p /etc/apt/keyrings \
 && curl -fsSL https://repo.pigsty.io/key | gpg --dearmor -o /etc/apt/keyrings/pigsty.gpg \
 && DISTRO="$(lsb_release -cs)" \
 && echo "deb [signed-by=/etc/apt/keyrings/pigsty.gpg] https://repo.pigsty.io/apt/pgsql/${DISTRO} ${DISTRO} main" \
      > /etc/apt/sources.list.d/pigsty.list \
 && apt-get update \
 && apt-get install -y --no-install-recommends \
      libcurl4 libsodium23 \
      postgresql-${PGVERSION}-pgsodium \
      postgresql-${PGVERSION}-vault \
      postgresql-${PGVERSION}-pg-graphql \
      postgresql-${PGVERSION}-supautils \
      postgresql-${PGVERSION}-pg-safeupdate \
      postgresql-${PGVERSION}-pgjwt \
      postgresql-${PGVERSION}-pg-jsonschema \
      postgresql-${PGVERSION}-wrappers \
      postgresql-${PGVERSION}-pgmq \
      postgresql-${PGVERSION}-pg-tle \
      postgresql-${PGVERSION}-index-advisor \
 && rm -rf /var/lib/apt/lists/*

COPY --from=pg-net-builder /tmp/pg_net-install/ /

# pgsodium refuses to load from shared_preload_libraries without a getkey
# script. This one is DEVELOPMENT GRADE: a fresh random key on every start, so
# anything pgsodium encrypts does not survive a restart. Mount a real key over
# this path before storing anything you need to read back.
RUN printf '%s\n' '#!/bin/sh' 'od -vN 32 -An -tx1 /dev/urandom | tr -d " \n"' \
      > "/usr/share/postgresql/${PGVERSION}/extension/pgsodium_getkey" \
 && chmod 0755 "/usr/share/postgresql/${PGVERSION}/extension/pgsodium_getkey" \
 && chown postgres:postgres "/usr/share/postgresql/${PGVERSION}/extension/pgsodium_getkey"

COPY --chown=postgres:postgres migrations/ /supabase-migrations/
COPY --chown=postgres:postgres scripts/supabase_post_init.sh /scripts/supabase_post_init.sh
COPY --chown=postgres:postgres scripts/lib-migrate.sh /scripts/lib-migrate.sh
COPY --chown=postgres:postgres scripts/migrate.sh /scripts/migrate.sh

# Spilo's own post_init.sh is what Patroni invokes; appending to it is how this
# hooks in without replacing anything Spilo does first (its admin roles, the
# metric_helpers schema, the log foreign tables).
RUN chmod 0755 /scripts/supabase_post_init.sh /scripts/migrate.sh \
 && printf '\n%s\n%s\n' '# Supabase bootstrap (added by supabase-spilo)' \
      '/scripts/supabase_post_init.sh "$@"' >> /scripts/post_init.sh

USER postgres

LABEL org.opencontainers.image.title="supabase-spilo" \
      org.opencontainers.image.description="Zalando Spilo with the Supabase extension set and bootstrap migrations" \
      org.opencontainers.image.source="https://github.com/zoc/supabase-spilo" \
      org.opencontainers.image.licenses="Apache-2.0"
